# Generated by Django 3.2.12 on 2022-10-10 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('elegir_genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=1)),
                ('idioma', models.CharField(max_length=20)),
                ('cumpleaños', models.DateField()),
                ('staff', models.BooleanField()),
                ('moderador', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='comunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripción', models.CharField(max_length=100)),
                ('juego', models.CharField(max_length=20)),
                ('numero_jugadores', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('limite_jugadores', models.PositiveBigIntegerField()),
                ('juego', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('idioma', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameseek_app.cliente')),
            ],
        ),
    ]
