# Generated by Django 4.1.1 on 2022-10-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameseek_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='communitie',
            new_name='community',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='languaje',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='languaje',
            new_name='language',
        ),
    ]
