# Generated by Django 4.1.1 on 2022-10-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameseek_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
