# Generated by Django 4.1.3 on 2022-12-18 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameseek_app', '0004_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='game',
        ),
        migrations.AddField(
            model_name='client',
            name='cargo',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('MODERATOR', 'Moderator'), ('STAFF', 'Staff')], default='STANDARD', max_length=10),
        ),
        migrations.AddField(
            model_name='community',
            name='juegos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameseek_app.game'),
        ),
        migrations.AddField(
            model_name='event',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameseek_app.community'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default='YYYY-MM-DD'),
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameseek_app.community')),
                ('comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
