# Generated by Django 4.1.3 on 2022-12-18 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameseek_app', '0005_remove_community_game_client_cargo_community_juegos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
