# Generated by Django 4.1.3 on 2023-01-07 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameseek_app', '0007_community_cliente_delete_ingresos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='game',
        ),
    ]
